/**
 * Regenerates data/roles/<role>.json from the JD texts in data/raw_jds/<role>/.
 *
 *   pnpm build:roles                 compare only, writes nothing
 *   pnpm build:roles --write         overwrite the role files
 *   pnpm build:roles --role=devops-engineer
 *
 * Frequencies are the share of JD files mentioning a skill, matched against
 * data/skill_taxonomy.json aliases. The committed role files are curated
 * aggregates over 20 listings of which five full texts ship in the repo, so a
 * run over those five files will differ: that difference is the point of the
 * comparison table, and the pipeline is how a larger corpus gets folded in.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { getRoleStats } from '../lib/dataset';
import { findSkillsInText, getSkillCategory } from '../lib/skills/taxonomy';
import { ROLE_SLUGS, type RoleSkill, type RoleSlug } from '../types/data';

const RAW_ROOT = path.join(process.cwd(), 'data', 'raw_jds');
const ROLE_ROOT = path.join(process.cwd(), 'data', 'roles');
const MIN_FREQUENCY = 0.2;

async function readJdTexts(slug: RoleSlug): Promise<string[]> {
  const dir = path.join(RAW_ROOT, slug);
  const files = (await readdir(dir)).filter((name) => name.endsWith('.txt')).sort();
  return Promise.all(files.map((name) => readFile(path.join(dir, name), 'utf8')));
}

function computeFrequencies(texts: string[]): RoleSkill[] {
  const counts = new Map<string, number>();
  for (const text of texts) {
    for (const skill of findSkillsInText(text)) {
      counts.set(skill, (counts.get(skill) ?? 0) + 1);
    }
  }

  return [...counts.entries()]
    .map(([skill, count]) => ({
      skill,
      frequency: Number((count / texts.length).toFixed(2)),
      category: getSkillCategory(skill),
    }))
    .filter((entry) => entry.frequency >= MIN_FREQUENCY)
    .sort((a, b) => b.frequency - a.frequency || a.skill.localeCompare(b.skill));
}

function printComparison(slug: RoleSlug, computed: RoleSkill[]): void {
  const curated = new Map(getRoleStats(slug).skills.map((s) => [s.skill, s.frequency]));
  const rows = computed.map((entry) => ({
    skill: entry.skill,
    from_raw_jds: entry.frequency,
    committed: curated.get(entry.skill) ?? '-',
  }));
  const onlyCurated = [...curated.keys()].filter(
    (skill) => !computed.some((entry) => entry.skill === skill),
  );

  process.stdout.write(`\n${slug}: ${computed.length} skills found in raw JDs\n`);
  console.table(rows);
  if (onlyCurated.length > 0) {
    process.stdout.write(
      `Committed but not found in the sampled texts: ${onlyCurated.join(', ')}\n`,
    );
  }
}

async function run(): Promise<void> {
  const write = process.argv.includes('--write');
  const roleArg = process.argv.find((arg) => arg.startsWith('--role='))?.split('=')[1];
  const targets: RoleSlug[] = roleArg
    ? ROLE_SLUGS.filter((slug) => slug === roleArg)
    : [...ROLE_SLUGS];

  if (targets.length === 0) throw new Error(`Unknown role: ${roleArg}`);

  for (const slug of targets) {
    const texts = await readJdTexts(slug);
    const computed = computeFrequencies(texts);
    printComparison(slug, computed);

    if (!write) continue;
    const existing = getRoleStats(slug);
    const document = {
      role: existing.role,
      jd_count: texts.length,
      source_note: `Generated by scripts/build-role-stats.ts from ${texts.length} JD texts in data/raw_jds/${slug}/.`,
      skills: computed,
    };
    await writeFile(
      path.join(ROLE_ROOT, `${slug}.json`),
      `${JSON.stringify(document, null, 2)}\n`,
      'utf8',
    );
    process.stdout.write(`Wrote data/roles/${slug}.json from ${texts.length} JD texts\n`);
  }

  if (!write) {
    process.stdout.write('\nNothing written. Re run with --write to overwrite the role files.\n');
  }
}

run().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
